[workspace]
members = ["src-tauri"]
resolver = "3"

[workspace.package]
version = "1.0.0"
description = "A lightweight Minecraft Java Edition join client powered by sculk"
repository = "https://github.com/SeaLantern-Studio/SeaLantern-Connect"
authors = ["SeaLantern-Studio"]
edition = "2024"
license = "Apache-2.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
