[package]
name = "gds3d-viewport"
version = "0.1.4"
edition = "2024"
description = "WGPU viewport for gds3d."
license = "MIT"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
crc32fast = "1.5"
earcutr = "0.5"
eframe = { version = "0.36", default-features = false, features = ["wgpu", "wayland", "x11"] }
flate2 = "1.1"
